version: '3.8'

services:
  nginx:
    image: nginx:1.18
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/node91.webte.fei.stuba.sk
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php

  php:
    build: .
    working_dir: /var/www/node91.webte.fei.stuba.sk
    volumes:
      - ./src:/var/www/node91.webte.fei.stuba.sk
    command: php-fpm

  db:
    image: mysql:8.0
    container_name: mysql-db
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: mojeHeslo.123
      MYSQL_DATABASE: z4_webte2
      MYSQL_USER: xpitkakester
      MYSQL_PASSWORD: mojeHeslo.123
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: mojeHeslo.123
    depends_on:
      - db

volumes:
  db_data:
