version: '3.8'

services:
  # Nginx webserver service
  nginx:
    image: nginx:1.18
    ports:
      - 80:80
    volumes:
      - C:\\Users\\PyKej\\Documents\\SCHOOL-6\\WEBTE2\\Z4-WEBTE2:/var/www/node91.webte.fei.stuba.sk
      - C:\\Users\\PyKej\\Documents\\SCHOOL-6\\WEBTE2\\Z4-WEBTE2\\.docker\\nginx\\conf.d:/etc/nginx/conf.d
    depends_on:
      - php

  # PHP-FPM service
  php:
    build: C:\\Users\\PyKej\\Documents\\SCHOOL-6\\WEBTE2\\Z4-WEBTE2\\.docker\\php
    working_dir: /var/www/www/node91.webte.fei.stuba.sk
    volumes:
      - C:\\Users\\PyKej\\Documents\\SCHOOL-6\\WEBTE2\\Z4-WEBTE2:/var/www/node91.webte.fei.stuba.sk
    depends_on:
      mysql:
        condition: service_healthy

  #MySQL service
  mysql:
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_ROOT_PASSWORD: super-silne-heslo
      # MYSQL_ROOT_HOST: "%"
      MYSQL_USER: xpitkakester
      MYSQL_PASSWORD: mojeHeslo.123
      MYSQL_DATABASE: z4-webte2
    volumes:
      - C:\\Users\\PyKej\\Documents\\SCHOOL-6\\WEBTE2\\Z4-WEBTE2\\.docker\\mysql\\my.cnf:/etc/mysql/mysql.cnf
      - C:\\Users\\PyKej\\Documents\\SCHOOL-6\\WEBTE2\\Z4-WEBTE2\\.database:/docker-entrypoint-initdb.d
      - mysqldata:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 5s
      retries: 10
  
  # phpMyAdmin interface
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
    depends_on:
      mysql:
        condition: service_healthy
# Volumes
volumes:
  mysqldata: